### ISSUE TITLE
Does not post message to chat

### ISSUE THREAD

**Issue by PeskyPotato** [Rocketeer999/book-downloader#1]
I've tried multiple ways on invoking the program, such as 
```
python3 downloader.py beauty markwatson
Searching ...
```

```
python3 downloader.py
Usage: testbot <searchterm> <nickname>
Enter Search Term(s):
farseer
Enter Nickname:
ausername
Searching ...
```
and hard coding the search term and username in the python file. It always results in the same error after waiting for a few seconds.
```
Unknown encoding encountered. See 'Decoding Input'
in https://pypi.python.org/pypi/irc for details.

Traceback (most recent call last):
  File "downloader.py", line 177, in <module>
    main()
  File "downloader.py", line 174, in main
    bot.start()
  File "/home/bender/.local/lib/python3.6/site-packages/irc/bot.py", line 334, in start
    super(SingleServerIRCBot, self).start()
  File "/home/bender/.local/lib/python3.6/site-packages/irc/client.py", line 1192, in start
    self.reactor.process_forever()
  File "/home/bender/.local/lib/python3.6/site-packages/irc/client.py", line 845, in process_forever
    consume(infinite_call(one))
  File "/home/bender/.local/lib/python3.6/site-packages/more_itertools/recipes.py", line 160, in consume
    deque(iterator, maxlen=0)
  File "/home/bender/.local/lib/python3.6/site-packages/jaraco/itertools.py", line 412, in <genexpr>
    return (f() for _ in itertools.repeat(None))
  File "/home/bender/.local/lib/python3.6/site-packages/irc/client.py", line 826, in process_once
    self.process_data(in_)
  File "/home/bender/.local/lib/python3.6/site-packages/irc/client.py", line 790, in process_data
    conn.process_data()
  File "/home/bender/.local/lib/python3.6/site-packages/irc/client.py", line 270, in process_data
    for line in self.buffer:
  File "/home/bender/.local/lib/python3.6/site-packages/jaraco/stream/buffer.py", line 105, in lines
    self.handle_exception()
  File "/home/bender/.local/lib/python3.6/site-packages/jaraco/stream/buffer.py", line 103, in lines
    yield line.decode(self.encoding, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 66: invalid start byte
```

I've logged onto the irc chat and monitored the script, it successfully joins but a message never gets sent.

Thank you for writing this script, I've tried to do my own but it was not as successful. Hopefully, I can figure out what is causing this error in your script.

**Comment by Rocketeer999** [comment]
The IRC moderators made several changes to their channel that effectively break this bot. 

I'll look into fixing it if and when I have the time.
